export const API_ROUTES = {
  login: "/api/auth/login",
  me: "/api/auth/me",

  adminCampuses: "/api/admin/campuses",
  adminCycles: "/api/admin/cycles",
  adminClassrooms: "/api/admin/classrooms",
  adminBillingConcepts: "/api/admin/billing-concepts",
  adminBillingSchedule: "/api/admin/billing-schedule",
  adminAttendancePolicy: "/api/admin/attendance-policy",
  adminExportCajaArequipa: "/api/admin/exports/caja-arequipa",
  adminEndpoints: "/api/admin/endpoints",
  adminModels: "/api/admin/models",
  dashboardSecretaryOverview: "/api/dashboard/secretary/overview",
  classroomOptions: "/api/classrooms/options",
  attendanceOpenSession: "/api/attendance/sessions/open",
  attendanceClassroomOptions: "/api/attendance/classrooms/options",
  attendanceIntakeView: (sessionId) => `/api/attendance/sessions/${sessionId}/intake-view`,
  attendanceUpdateSession: (sessionId) => `/api/attendance/sessions/${sessionId}`,
  attendanceScan: (sessionId) => `/api/attendance/sessions/${sessionId}/scan`,
  attendanceJustifyRecord: (recordId) => `/api/attendance/records/${recordId}/justification`,
  attendanceJustifyRecordsBatch: "/api/attendance/records/justification-batch",
  attendanceRecentJustifications: "/api/attendance/justifications/recent",
  attendanceClassroomDailyReport: (classroomId) => `/api/attendance/classrooms/${classroomId}/daily-report`,
  attendanceClassroomMonthlySummary: (classroomId) => `/api/attendance/classrooms/${classroomId}/monthly-summary`,
  attendanceStudentMonthlySummary: (studentId) => `/api/attendance/students/${studentId}/monthly-summary`,

  students: "/api/students",
  studentsByCampus: (campus) => `/api/students/campus/${campus}`,
  studentDetail: (id) => `/api/students/${id}`,
  studentSummary: (id) => `/api/students/${id}/summary`,
  studentClassroom: (id) => `/api/students/${id}/classroom`,
  studentIdentity: (id) => `/api/students/${id}/identity`,
  studentInternalNotes: (id) => `/api/students/${id}/internal-notes`,
  studentIntake: "/api/students/intake",
  studentsSearch: "/api/students/search",
  studentsPrintCards: "/api/students/print-cards",
  studentsUnassigned: "/api/students/unassigned",
  studentsUnassignedSearch: "/api/students/unassigned/search",
  createTutor: "/api/tutors",
  tutorsSearch: "/api/tutors/search",
  tutorById: (id) => `/api/tutors/${id}`,
  personById: (id) => `/api/people/${id}`,

  enrollments: "/api/enrollments",
  enrollmentFinalize: "/api/enrollments/finalize",
  enrollmentsList: "/api/enrollments",
  enrollmentDetail: (id) => `/api/enrollments/${id}`,
  enrollmentStatus: (id) => `/api/enrollments/${id}/status`,
  enrollmentClassroomCapacity: (classroomId) => `/api/enrollments/classrooms/${classroomId}/capacity`,
  charges: "/api/charges",
  chargeDetail: (id) => `/api/charges/${id}`,
  paymentsCreate: "/api/payments",
  paymentReceiptCorrection: (id) => `/api/payments/${id}/receipt`,
  paymentsDailySummary: "/api/payments/daily-summary",
  paymentsDailyTransactions: "/api/payments/daily-transactions",
  paymentsDebtors: "/api/payments/debtors",
  paymentsDebtorsSearch: "/api/payments/debtors/search",
  payments: "/api/payments",
  studentAccountStatement: (studentId) => `/api/students/${studentId}/account-statement`,
  studentCharges: (studentId) => `/api/students/${studentId}/charges`,
  studentPayments: (studentId) => `/api/students/${studentId}/payments`,
  // TODO (backend): support allocations to charges and update outstanding amounts.
};
