export const API_ROUTES = {
  login: "/api/auth/login",
  me: "/api/auth/me",

  adminCampuses: "/api/admin/campuses",
  adminCycles: "/api/admin/cycles",
  adminClassrooms: "/api/admin/classrooms",
  adminBillingConcepts: "/api/admin/billing-concepts",
  adminBillingSchedule: "/api/admin/billing-schedule",
  adminAttendancePolicy: "/api/admin/attendance-policy",
  adminEndpoints: "/api/admin/endpoints",
  adminModels: "/api/admin/models",
  dashboardSecretaryOverview: "/api/dashboard/secretary/overview",
  classroomOptions: "/api/classrooms/options",
  attendanceOpenSession: "/api/attendance/sessions/open",
  attendanceClassroomOptions: "/api/attendance/classrooms/options",
  attendanceIntakeView: (sessionId) => `/api/attendance/sessions/${sessionId}/intake-view`,
  attendanceUpdateSession: (sessionId) => `/api/attendance/sessions/${sessionId}`,
  attendanceScan: (sessionId) => `/api/attendance/sessions/${sessionId}/scan`,
  attendanceJustifyRecord: (recordId) => `/api/attendance/records/${recordId}/justification`,
  attendanceJustifyRecordsBatch: "/api/attendance/records/justification-batch",
  attendanceRecentJustifications: "/api/attendance/justifications/recent",
  attendanceClassroomDailyReport: (classroomId) => `/api/attendance/classrooms/${classroomId}/daily-report`,
  attendanceClassroomMonthlySummary: (classroomId) => `/api/attendance/classrooms/${classroomId}/monthly-summary`,
  attendanceStudentMonthlySummary: (studentId) => `/api/attendance/students/${studentId}/monthly-summary`,

  students: "/api/students",
  studentsByCampus: (campus) => `/api/students/campus/${campus}`,
  studentSummary: (id) => `/api/students/${id}/summary`,
  studentCycleStatus: (id) => `/api/students/${id}/cycle-status`,
  studentClassroom: (id) => `/api/students/${id}/classroom`,
  studentIdentity: (id) => `/api/students/${id}/identity`,
  studentInternalNotes: (id) => `/api/students/${id}/internal-notes`,
  studentIntake: "/api/students/intake",
  studentsSearch: "/api/students/search",
  studentsPrintCards: "/api/students/print-cards",
  studentsUnassigned: "/api/students/unassigned",
  studentsUnassignedSearch: "/api/students/unassigned/search",
  createTutor: "/api/tutors",
  tutorById: (id) => `/api/tutors/${id}`,
  personById: (id) => `/api/people/${id}`,

  familiesSearch: "/api/families/search",
  familyDetail: (id) => `/api/families/${id}`,
  families: "/api/families",
  familiesLinkStudent: "/api/families/link-student",
  familyTutors: (id) => `/api/families/${id}/tutors`,
  familyPrimaryTutor: (id) => `/api/families/${id}/primary-tutor`,
  familyUnlinkStudent: (familyId) => `/api/families/${familyId}/unlink-student`,

  enrollments: "/api/enrollments",
  enrollmentsList: "/api/enrollments",
  enrollmentDetail: (id) => `/api/enrollments/${id}`,
  enrollmentClassroomCapacity: (classroomId) => `/api/enrollments/classrooms/${classroomId}/capacity`,
  enrollmentCases: "/api/enrollment-cases",
  enrollmentIntakeSearch: "/api/enrollments/intake-search",
  // TODO (backend): implement EnrollmentCase draft flow (create/list/detail) with fields: id, campusId/campusCode, cycleId, status, familyId, enrollmentStudents[].
  enrollmentCaseDetail: (id) => `/api/enrollment-cases/${id}`,
  enrollmentCaseConfirm: (id) => `/api/enrollment-cases/${id}/confirm`,
  // TODO (backend): confirm should return updated case + summary { studentsConfirmedCount, chargesCreatedCount }.
  enrollmentCaseAddStudent: (id) => `/api/enrollment-cases/${id}/students`,
  enrollmentCaseUpdateStudent: (caseId, esId) => `/api/enrollment-cases/${caseId}/students/${esId}`,
  enrollmentCaseSetFamily: (id) => `/api/enrollment-cases/${id}/family`,
  enrollmentCaseRemoveStudent: (caseId, esId) => `/api/enrollment-cases/${caseId}/students/${esId}`,
  charges: "/api/charges",
  paymentsCreate: "/api/payments",
  paymentsDebtors: "/api/payments/debtors",
  paymentsDebtorsSearch: "/api/payments/debtors/search",
  payments: "/api/payments",
  studentAccountStatement: (studentId) => `/api/students/${studentId}/account-statement`,
  studentCharges: (studentId) => `/api/students/${studentId}/charges`,
  studentPayments: (studentId) => `/api/students/${studentId}/payments`,
  // TODO (backend): support allocations to charges and update outstanding amounts.
};
